### ISSUE TITLE
Can't use GenerateProduct

### ISSUE THREAD

**Issue by Amadeus-AI** [Taromaruu/WaifuLabs#1]
Hi, thanks for the great work.
I tried the "Generate a waifu product (Waifu製品を生成する)" part, but it didn't work.
![圖片](https://user-images.githubusercontent.com/23719775/133592692-4fe74020-3ae4-49c1-b0bb-e9189676b2fb.png)

**Comment by TaromaruYuki** [comment]
I have got a friend to fix the issue later today. I currently cannot due to personal problems. Thanks for understanding.

**Comment by TaromaruYuki** [comment]
I will update the package soon.
